### ISSUE TITLE
Mismatch @arcgis/core version

### ISSUE THREAD

**Issue by sweco-nlgucu** [geocortex/vertigis-web-sdk#31]
Hi there,

To be sure that the imports work from my intellisense (with VSC), I've added a few devDependencies to the package.json of the project that was generated using `npx @vertigis/web-sdk create <library-name>`:
```json
{
    "devDependencies": {
        "@arcgis/core":"4.21.2",
        "@types/react":"17.0.24",
        "@types/react-dom":"17.0.9",
        "@types/react-window":"1.8.5",
        "@vertigis/arcgis-extensions":"33.5.5",
        "@vertigis/react-ui":"8.12.0",
        "@vertigis/viewer-spec":"43.0.0",
        "@vertigis/web": "5.15.0",
        "@vertigis/web-sdk": "1.4.0",
        "typescript": "^4.3.2"
    }
}
```
These versions should match those needed for web 5.15. However, the `@arcgis/core` dependendency gives an error with `npm install`:
```ps1
npm ERR! Could not resolve dependency:
npm ERR! peer @arcgis/core@"~4.19.0" from @vertigis/arcgis-extensions@33.5.5
```

It seems that the peerDependency in the `@vertigis/arcgis-extension` library causes this:
```json
  "peerDependencies": {
    "@arcgis/core": "~4.19.0",
    "tslib": "^2.3.1"
  },
```

Regards,
Guus

**Comment by eric-parsons** [comment]
Hi Guus,

Thanks for bringing this to our attention. I'm not sure how this peer dependency version got out of sync. I have a fix coming which will be released in 5.16.1 of VertiGIS Studio Web, which will likely be out in the next week or two at most. Thanks for your patience.

Eric

**Comment by eric-parsons** [comment]
@sweco-nlgucu , VertiGIS Studio Web 5.16.1 is now live and an updated package was published to npm. Please let me know if this resolves the errors you were experiencing and I'll close this issue.

**Comment by sweco-nlgucu** [comment]
@eric-parsons this seems to be fixed now, thanks 👍

**Comment by eric-parsons** [comment]
Great, glad it's fixed now. We'll try to keep an eye on this for future releases.
